version: '3.7'
services:
  leo_gazebo:
    image: local/leo_gazebo:humble
    restart: "no"
    container_name: leo_gazebo
    environment:
      - ROS_NAMESPACE=leo_sim
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY
      - PUID=0
      - PGID=0
    privileged: true
    ipc: host
    network_mode: host
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ./gazebo_leorover_model:/home/leo/gazebo_leorover_model
      - ./environment_models:/home/leo/environment_models
      - ./ros2_ws/src/leorover_gazebo_bridge:/home/leo/ros2_ws/src/leorover_gazebo_bridge
    tty: true
    stdin_open: true
    # runtime: nvidia # Instead of --gpus all
    command: gz sim lunar_landscape_prototype.sdf
