controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['wheel_RL_joint', 'wheel_FL_joint']
    right_wheel_names: ['wheel_RR_joint', 'wheel_FR_joint']

    wheel_separation: 0.33
    wheels_per_side: 2
    wheel_radius: 0.0625
    wheel_separation_multiplier: 1.91

    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.03]
    twist_covariance_diagonal: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.001]

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    publish_rate: 20.0

    open_loop: false

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    velocity_rolling_window_size: 10

    preserve_turning_radius: true

    # Publish limited velocity
    publish_limited_velocity: true

    linear/x:
      has_velocity_limits: true
      max_velocity: 0.4
      has_acceleration_limits: true
      max_acceleration: 0.8

    angular/z:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0